### ISSUE TITLE
异常TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by xi-yue-233** [ReiiNoki/nonebot-plugin-kuma-san#1]
Traceback (most recent call last):
  File "E:\qqbot-nonebot\Nonebot\nb2\bot.py", line 39, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "D:\python-software\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\python-software\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\python-software\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\python-software\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\python-software\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python-software\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\python-software\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\python-software\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\python-software\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\python-software\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\python-software\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\python-software\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\python-software\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\python-software\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "D:\python-software\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\python-software\lib\site-packages\nonebot_plugin_kuma_san\__init__.py", line 47, in _
    result_str = '现在的涂地场地：\n' + await request('regular', args[1])
TypeError: can only concatenate str (not "NoneType") to str

**Comment by xi-yue-233** [comment]
代理问题，关闭代理之后正常了
