### ISSUE TITLE
我在使用时遇到了 TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by devilhuixie** [ReiiNoki/nonebot-plugin-kuma-san#2]
使用python版本为3.10 具体日志如下，是哪里环境出现问题吗？ 

> 02-03 19:50:21 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kuma_san)
02-03 19:50:21 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_kuma_san)
02-03 19:50:21 [DEBUG] nonebot | Running handler Dependent(call=_)
02-03 19:50:22 [INFO] uvicorn | 127.0.0.1:3784 - "GET /api/accounts HTTP/1.1" 200
02-03 19:50:22 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kuma_san) running complete
02-03 19:50:22 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kuma_san) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\devil\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\devil\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\devil\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\devil\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\devil\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\devil\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot_plugin_kuma_san\__init__.py", line 25, in _
    result_str = '以下是接下来的鲑鱼跑场地：\n' + await request('salmon_run', 'schedule')
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot_plugin_kuma_san\__init__.py", line 147, in request
    results = await list_stage(name, time)
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot_plugin_kuma_san\services\stage_service.py", line 61, in list_stage
    salmon_run_to_string(result['start_time'], result['end_time'], result['stage']['name'], weapons[0],
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot_plugin_kuma_san\services\stage_service.py", line 38, in salmon_run_to_string
    return SalmonRun(start, end, stage, weapon1, weapon2, weapon3, weapon4).to_string()
  File "D:\Program Files (x86)\QQRobot\first_robot\.venv\lib\site-packages\nonebot_plugin_kuma_san\model.py", line 51, in to_string
    return self.start + ' - ' + self.end + '\n' + self.stage + '\n' + self.weapon1 + ' ' + self.weapon2 + '\n' + self.weapon3 + ' ' + self.weapon4
TypeError: can only concatenate str (not "NoneType") to str
02-03 19:50:22 [DEBUG] nonebot | Stop event propagation
02-03 19:50:22 [DEBUG] nonebot | Checking for matchers completed

**Comment by devilhuixie** [comment]
只有打工和祭典会报错，其它则正常

**Comment by devilhuixie** [comment]
已解决！
问题在翻译上面，对于工作刮水刀的日语有变化，造成为空，把工作刮水刀的日语替换为 ジムワイパー  成功！
